version: "3.8"

services:
    api-gateway:
        build: .
        container_name: api-gateway
        ports:
            - "8000:8000"
        environment:
            - NODE_ENV=production
            - PORT=8000
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=24h
            - USER_SERVICE_URL=http://user-service:8081
            - PRODUCT_SERVICE_URL=http://product-service:8082
            - ORDER_SERVICE_URL=http://order-service:8083
            - PAYMENT_SERVICE_URL=http://payment-service:8084
            - NOTIFICATION_SERVICE_URL=http://notification-service:8085
            - RATE_LIMIT_WINDOW_MS=900000
            - RATE_LIMIT_MAX=100
            - LOG_LEVEL=info
        networks:
            - ecommerce-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    ecommerce-network:
        driver: bridge
