version: "3.8"

services:
    api-gateway:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-gateway
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - JWT_SECRET=${JWT_SECRET}
            - SERVICE_SECRET=${SERVICE_SECRET}
            - JWT_EXPIRES_IN=24h
            - USER_SERVICE_URL=http://user-service:8081
            - PRODUCT_SERVICE_URL=http://product-service:8082
            - ORDER_SERVICE_URL=http://order-service:8083
            - PAYMENT_SERVICE_URL=http://payment-service:8084
            - NOTIFICATION_SERVICE_URL=http://notification-service:8085
            - RATE_LIMIT_WINDOW_MS=900000
            - RATE_LIMIT_MAX=100
        networks:
            - ecommerce-network
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8000/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    # Optional: Include Redis for rate limiting
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - ecommerce-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    redis_data:

networks:
    ecommerce-network:
        driver: bridge
