apiVersion: v1
kind: ConfigMap
metadata:
    name: api-gateway-config
    namespace: ecommerce
data:
    NODE_ENV: "production"
    PORT: "8000"
    USER_SERVICE_URL: "http://user-service:8081"
    PRODUCT_SERVICE_URL: "http://product-service:8082"
    ORDER_SERVICE_URL: "http://order-service:8083"
    PAYMENT_SERVICE_URL: "http://payment-service:8084"
    NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
    RATE_LIMIT_WINDOW_MS: "900000"
    RATE_LIMIT_MAX: "100"
    LOG_LEVEL: "info"
